import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const code=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
function picker(id='file'){const files=[],loaded=[],jobs=[];const input={files};Object.defineProperty(input,'value',{set(){files.length=0;}});const context={$:name=>name===id?input:{},run:fn=>jobs.push(Promise.resolve().then(fn)),loadFile:file=>loaded.push(file)};vm.runInNewContext(code.match(/for\(const id of \['file','deviceFile'\]\).*?\.onchange=e=>\{.*?\};/)[0],context);return {files,loaded,jobs,input};}
test('file reference survives clearing the picker before async loading',async()=>{const p=picker(),file=new Blob(['picture']);p.files.push(file);p.input.onchange({target:p.input});assert.equal(p.files.length,0);await Promise.all(p.jobs);assert.equal(p.loaded[0],file);});
test('same file can be selected again, cancellation does not load',async()=>{const p=picker(),file=new Blob(['same']);p.input.onchange({target:p.input});assert.equal(p.jobs.length,0);for(let i=0;i<2;i++){p.files.push(file);p.input.onchange({target:p.input});await Promise.all(p.jobs);}assert.deepEqual(p.loaded,[file,file]);});
test('Files picker can select the same file again',async()=>{const p=picker('deviceFile'),file=new Blob(['same']);for(let i=0;i<2;i++){p.files.push(file);p.input.onchange({target:p.input});await Promise.all(p.jobs);}assert.deepEqual(p.loaded,[file,file]);});
test('drag/drop preserves the file when the drag store expires',async()=>{const files=[new Blob(['drop'])],expected=files[0],jobs=[],loaded=[],target={classList:{remove(){}}};vm.runInNewContext(code.match(/\$\('dropzone'\)\.ondrop=e=>\{.*?\};/)[0],{$:()=>target,run:fn=>jobs.push(Promise.resolve().then(fn)),loadFile:f=>loaded.push(f)});target.ondrop({preventDefault(){},dataTransfer:{files}});files.length=0;await Promise.all(jobs);assert.equal(loaded[0],expected);});
function decoder(){let opened;const context={Uint8Array,Blob,MAX_PIXELS:24000000,readDataUrl:async b=>{opened=b;return 'data:test';},URL:{createObjectURL(b){opened=b;return 'blob:test';},revokeObjectURL(){}},imageFrom:async()=>({width:2,height:2}),canvas:(w,h)=>({width:w,height:h}),ctx:()=>({drawImage(){}})};vm.runInNewContext(code.slice(code.indexOf('async function decode('),code.indexOf('async function loadFile(')),context);return {decode:context.decode,opened:()=>opened};}
for(const [type,bytes] of [['image/png',[137,80,78,71,13,10,26,10]],['image/jpeg',[255,216,255,224]],['image/webp',[82,73,70,70,0,0,0,0,87,69,66,80]]])test(`recognizes ${type} without MIME metadata`,async()=>{const d=decoder();await d.decode(new Blob([Uint8Array.from(bytes)]));assert.equal(d.opened().type,type);});
test('does not trust a misleading PNG MIME label',async()=>{const d=decoder();await assert.rejects(d.decode(new Blob(['not an image'],{type:'image/png'})),/Dateiformat/);assert.equal(d.opened(),undefined);});
