const assert=require('node:assert/strict');
const {harness}=require('./ui-harness.cjs');
(async()=>{
 const h=harness(),{$,document}=h;
 assert.equal($('checkFile').disabled,true);assert.equal($('removeMode').value,'edge');
 await h.load();assert.equal($('preview').hidden,false,$('toast').textContent);assert.equal($('undo').disabled,true);
 await h.change('width','0.5');await h.change('height','0.5');await h.change('remove',true);
 assert.equal($('undo').disabled,false);
 await h.check('png');assert.equal($('proofArea').hidden,false,$('checkStatus').textContent);
 assert.equal($('exportPng').disabled,true);assert.match($('checkAlpha').textContent,/transparente Pixel/);
 h.approve();assert.equal($('exportPng').disabled,false);await $('exportPng').onclick();
 assert.equal(h.downloads.length,1);const b=h.downloads[0].blob;const {Image,createCanvas}=require('@napi-rs/canvas');const im=new Image();im.src=Buffer.from(await b.arrayBuffer());assert.equal(im.width,60);assert.equal(im.height,60);
 await im.decode();const decoded=createCanvas(60,60),dg=decoded.getContext('2d');dg.drawImage(im,0,0);assert.equal(dg.getImageData(0,0,1,1).data[3],0);assert.equal(dg.getImageData(30,30,1,1).data[3],255,'Exterior removal must preserve the white enclosed detail');
 await h.change('removeMode','all');assert.equal($('exportPng').disabled,true);assert.equal($('visualCheck').checked,false);
 await $('undo').onclick();assert.equal($('removeMode').value,'edge');assert.equal($('redo').disabled,false);
 await $('redo').onclick();assert.equal($('removeMode').value,'all');
 await h.check('pdf');h.approve();await $('exportPdf').onclick();assert.match(Buffer.from(await h.downloads[1].blob.arrayBuffer()).toString('latin1'),/\/SMask/);
 await h.check('svg');h.approve();await $('vectorExport').onclick();assert.match(await h.downloads[2].blob.text(),/<path/);
 await h.change('vectorThreshold','0');assert.equal($('vectorExport').disabled,true);
 await h.change('width','0');await h.check('png');assert.match($('checkStatus').textContent,/fehlgeschlagen/);assert.equal($('exportPng').disabled,true);
 await h.change('width','0.5');await h.change('height','0.5');
 await $('saveProject').onclick();const project=h.downloads.at(-1);assert.match(project.name,/\.texdtf$/);
 $('projectFile').onchange({target:{files:[project.blob],value:'project'}});await h.idle();assert.equal($('undo').disabled,true);await h.check('png');h.approve();await $('exportPng').onclick();
 assert.equal(h.network,0);
 assert.ok(document.querySelector('.stage').children.indexOf($('vectorSection'))<document.querySelector('.stage').children.indexOf($('preflight')));
 await $('reset').onclick();assert.equal($('remove').checked,false);await $('undo').onclick();assert.equal($('remove').checked,true);
 const white=createCanvas(20,20);white.getContext('2d').fillStyle='white';white.getContext('2d').fillRect(0,0,20,20);const whiteFile=new Blob([white.toBuffer('image/png')],{type:'image/png'});whiteFile.name='white.png';$('file').onchange({target:{files:[whiteFile],value:'white'}});await h.idle();await h.change('width','0.5');await h.change('remove',true);await h.check('png');h.approve();assert.equal($('exportPng').disabled,true);assert.match($('checkStatus').textContent,/leer/);
 const fromDownloads=new Blob([white.toBuffer('image/png')]);fromDownloads.name='downloads-motiv.png';$('deviceFile').onchange({target:{files:[fromDownloads],value:'downloads'}});await h.idle();assert.match($('fileInfo').textContent,/downloads-motiv/);assert.equal($('preview').hidden,false);assert.equal($('deviceFile').value,'');
 const unsupported=new Blob(['%PDF-1.4']);unsupported.name='falsche-datei.pdf';$('deviceFile').onchange({target:{files:[unsupported],value:'document'}});await h.idle();assert.match($('loadStatus').textContent,/PNG, JPG oder WebP/);assert.equal($('loadStatus').classList.contains('error'),true);
 console.log('PASS workflow: safe default and preserved white detail; local upload; history/redo/reset; proof and download gate; invalidation after edits; 60px PNG; PDF alpha; SVG; invalid size and empty result blocked; project roundtrip; vector before proof; zero app network calls.');
})().catch(e=>{console.error(e);process.exitCode=1;});
