'use strict';
const Core = (() => {
  function cents(v) { const s=String(v).trim().replace(',', '.'); if(!/^\d+(\.\d{1,2})?$/.test(s)) throw Error('Betrag mit höchstens zwei Nachkommastellen eingeben.'); const [a,b='']=s.split('.'); const n=Number(a)*100+Number(b.padEnd(2,'0')); if(!Number.isSafeInteger(n)||n>1000000000)throw Error('Betrag zu groß.');return n; }
  function qty(v){const n=Number(v);if(!Number.isInteger(n)||n<1||n>100000)throw Error('Stückzahl: ganze Zahl zwischen 1 und 100.000.');return n;}
  function variant(l){return JSON.stringify([l.maker,l.model,l.color,l.size]);}
  function total(lines){if(typeof Sales!=='undefined'&&lines.some(l=>l.priceBasis==='gross'))return Sales.total(lines);const groups={7:0,19:0};let ek=0;for(const l of lines){qty(l.qty);if(![7,19].includes(l.tax))throw Error('Steuersatz auswählen.');if(l.vk===null||!Number.isSafeInteger(l.vk)||l.vk<0)throw Error('Für jede Position einen eigenen Verkaufspreis festlegen.');if(!Number.isSafeInteger(l.ek)||l.ek<0)throw Error('Einkaufspreis prüfen.');groups[l.tax]+=l.qty*l.vk;ek+=l.qty*l.ek;}const net=groups[7]+groups[19];const taxes={7:Math.round(groups[7]*7/100),19:Math.round(groups[19]*19/100)};return {groups,taxes,net,tax:taxes[7]+taxes[19],gross:net+taxes[7]+taxes[19],ek};}
  const sizeOrder=['2XS','XS','S','M','L','XL','2XL','3XL','4XL','5XL','6XL'];
  function sizes(text){const s=String(text).trim().toUpperCase().replace(/XXXL/g,'3XL').replace(/XXL/g,'2XL').replace(/XXS/g,'2XS');if(s.includes('+')||s.includes(';'))return s.split(/[+;]/).flatMap(sizes);if(sizeOrder.includes(s))return [s];if(s.includes('-')){const [a,b]=s.split('-'),i=sizeOrder.indexOf(a),j=sizeOrder.indexOf(b);if(i>=0&&j>=i)return sizeOrder.slice(i,j+1);}if(/^\d{2,3}$/.test(s)||/^(ONE ?SIZE|UNISIZE|ONESIZE)$/.test(s))return [s];return [];}
  function tier(n,prices){const keys=Object.keys(prices).map(Number).filter(x=>x<=n).sort((a,b)=>b-a);if(!keys.length)throw Error('Keine passende EK-Staffel verfügbar.');return {min:keys[0],price:prices[keys[0]]};}
  function reprice(lines){for(const l of lines){const n=lines.filter(x=>variant(x)===variant(l)).reduce((s,x)=>s+x.qty,0);if(l.prices&&!l.manualEk){const t=tier(n,l.prices);l.ek=t.price;l.tier=t.min;}if(l.industry&&l.manualVk===false){const keys=Object.keys(l.industry).map(Number).filter(k=>k<=n).sort((a,b)=>b-a);l.vkTier=keys[0]??null;l.vk=l.vkTier===null?null:(l.priceBasis==='gross'?Math.round(l.industry[l.vkTier]*(100+l.tax)/100):l.industry[l.vkTier]);}}return lines;}
  function validState(s){if(!s||s.version!==1||typeof s.id!=='string'||!Number.isInteger(s.rev)||s.rev<0||!Array.isArray(s.customers)||!Array.isArray(s.orders)||!Array.isArray(s.docs)||!s.settings||!Array.isArray(s.catalog))throw Error('Unbekanntes oder beschädigtes Projektformat.');if(s.orders.length>10000)throw Error('Zu viele Aufträge.');for(const o of s.orders){if(!Array.isArray(o.lines)||!Array.isArray(o.placements))throw Error('Auftragsdaten beschädigt.');for(const l of o.lines){if(l.unit==='lfm'){if(!Number.isFinite(l.qty)||l.qty<2)throw Error('Meterware prüfen.');}else qty(l.qty);if(!Number.isSafeInteger(l.ek)||l.ek<0||!(l.vk===null||Number.isSafeInteger(l.vk)&&l.vk>=0)||![null,7,19].includes(l.tax))throw Error('Ungültige Positionsdaten.');}for(const p of o.placements){if(p.src&&!/^data:image\/(png|jpeg|webp);base64,/.test(p.src))throw Error('Unzulässiges Bildformat.');}}return s;}
  function excelCents(v){const n=Number(v);if(v===''||v==null||!Number.isFinite(n)||n<0)throw Error('Ungültiger Excel-Preis.');const rounded=Math.round((n+Number.EPSILON)*100);if(!Number.isSafeInteger(rounded)||rounded>1000000000)throw Error('Excel-Preis zu groß.');return rounded;}
  return {cents,excelCents,qty,total,sizes,tier,reprice,variant,validState};
})();
if(typeof module!=='undefined')module.exports=Core;
