function designSourceSelect(o,targetId){const sources=o.lines.filter(l=>l.id!==targetId&&o.placements.some(p=>p.lineId===l.id));if(!sources.length||o.placements.some(p=>p.lineId===targetId))return '';return select('designSource','Motive für diesen Artikel übernehmen',[['','Keine Motive übernehmen'],...sources.map(l=>[l.id,[l.description,l.model,l.color,l.size].filter(Boolean).join(' · ')+' ('+o.placements.filter(p=>p.lineId===l.id).length+' Motive)'])],sources[0].id)+'<p class="sub">Die vorhandenen Motive werden auf die neue Textilposition übertragen. Brust und Rücken erhöhen so jeweils ihre Druckmenge um die neue Stückzahl. Position und Maßstab am neuen Textil prüfen.</p>';}
function copyDesign(o,sourceId,targetId){if(!sourceId)return 0;const source=o.placements.filter(p=>p.lineId===sourceId),target=o.lines.find(l=>l.id===targetId);if(!target||!source.length||o.placements.some(p=>p.lineId===targetId))return 0;for(const p of source)o.placements.push({...structuredClone(p),id:uid(),lineId:targetId,calibration:null,backgrounds:{},needsReview:true});target.transfersPerItem=source.length;return source.length;}
function industryPreview(l,o){const copy=structuredClone(l);Core.reprice([...structuredClone(o.lines.filter(x=>x.id!==l.id)),copy]);return copy;}
function matchingIndustry(l){const matches=state.catalog.filter(r=>r.model===String(l.model).padStart(4,'0')&&r.colors.includes(l.color)&&r.sizes.includes(l.size)&&Object.keys(r.industry||{}).length);if(l.maker!=='HAKRO'||matches.length!==1)throw Error('Keine eindeutige HAKRO-Preiszeile für Modell, Farbe und Größe. Bitte aus dem Katalog auswählen.');return matches[0];}
function setupIndustryForm(l,o){const f=$('#lineForm');
const current=()=>({...l,maker:f.elements.maker.value,model:f.elements.model.value,color:f.elements.color.value,size:f.elements.size.value,qty:Number(f.elements.qty.value),tax:Number(f.elements.tax.value)});
const update=()=>{if(l.manualVk!==false)return;const row=current();if(['maker','model','color','size'].some(k=>row[k]!==l[k])){l.manualVk=true;$('#vkSource').textContent='Variante geändert: Preisquelle neu zuordnen oder VK manuell festlegen.';return;}const value=industryPreview(row,o);f.elements.vk.value=amount(Sales.gross(value));$('#vkSource').textContent=value.vk===null?'Keine passende Industriestaffel: VK manuell eingeben oder Menge erhöhen.':`Automatischer Brutto-VK · Industriepreis ab ${value.vkTier} Stück · ${l.vkSource||l.source||''}, Zeile ${l.vkSourceRow||l.sourceRow||''}`;};
bind('#useIndustry','click',()=>{const row=current();if(['maker','model','color','size'].some(k=>row[k]!==l[k]))throw Error('Geänderte Variante zuerst speichern, dann die passende Industriestaffel übernehmen.');const r=matchingIndustry(row);Object.assign(l,{industry:structuredClone(r.industry),priceBasis:'gross',manualVk:false,vkSource:r.source,vkSourceRow:r.row});update();});
f.elements.vk.addEventListener('input',()=>{l.manualVk=true;$('#vkSource').textContent='Manueller Brutto-VK: bleibt bei Mengenänderungen erhalten.';});for(const n of ['qty','maker','model','color','size','tax'])f.elements[n].addEventListener('input',update);update();}
function pickVariant(r){$('#modal').close();modal({title:`${esc(r.model)} ${esc(r.name)}`,body:`<form id="variantForm"><div class="grid">${select('color','Farbcode',r.colors,r.colors[0])}${select('size','Größe',r.sizes,r.sizes[0])}${input('qty','Stückzahl',1,'number','min="1" max="100000" required')}${input('transfersPerItem','Transfers je Textil (0 = unveredelt)',1,'number','min="0" max="100" required step="1"')}${input('vk','VK brutto (€) – automatisch oder manuell; darf zunächst offen bleiben','','text','inputmode="decimal"')}${Object.keys(r.prices||{}).length?'':input('ek','EK netto (€) – Händlerliste fehlt, manuell eintragen','','text','required inputmode="decimal"')}${select('tax','Mehrwertsteuer',[['','Bitte auswählen'],[7,'7 %'],[19,'19 %']],7)}</div>${designSourceSelect(order(),null)}<p id="vkSource" class="notice"></p>${button('useIndustry','Industriepreis wieder übernehmen')}<p class="sub">${Object.keys(r.prices||{}).length?'EK aus Händlerliste':'Kein Händler-EK importiert: manueller EK netto nötig.'} Quelle: ${esc(r.source)}, EU, Zeile ${r.row}. Die Staffel zählt alle Positionen mit gleichem Modell, gleicher Farbe und gleicher Größe in diesem Auftrag. EK bleibt getrennt.</p><button class="primary">In Auftrag übernehmen</button></form>`},()=>{const f=$('#variantForm'),lineId=uid();let manual=false;
const line=()=>({id:lineId,maker:'HAKRO',model:r.model,color:f.elements.color.value,size:f.elements.size.value,qty:Core.qty(f.elements.qty.value),priceBasis:'gross',tax:Number(f.elements.tax.value)||7,industry:structuredClone(r.industry||{}),manualVk:false});
const update=()=>{if(manual)return;try{const v=industryPreview(line(),order());f.elements.vk.value=amount(v.vk??null);$('#vkSource').textContent=v.vk==null?'Keine passende Industriestaffel. Die importierten Staffeln beginnen bei 10 Stück: du kannst jetzt einen Brutto-VK manuell eintragen oder die Position mit offenem VK übernehmen. Ein Angebot ist erst mit VK möglich.':`Brutto-VK ${euro(v.vk)} · Industriepreis ab ${v.vkTier} Stück`; }catch{f.elements.vk.value='';$('#vkSource').textContent='Gültige Menge eingeben.';}};
f.elements.vk.addEventListener('input',()=>{manual=true;$('#vkSource').textContent='Manueller Brutto-VK: bleibt bei Mengenänderungen erhalten.';});for(const n of ['qty','color','size','tax'])f.elements[n].addEventListener('input',update);bind('#useIndustry','click',()=>{manual=false;update();});
bind('#variantForm','submit',async e=>{e.preventDefault();const data=formData(f),tax=Number(data.tax);if(![7,19].includes(tax))throw Error('Steuersatz auswählen.');const missingEk=!Object.keys(r.prices||{}).length;if(missingEk&&!data.ek?.trim())throw Error('Händler-EK fehlt. EK netto manuell eintragen oder Händlerliste importieren.');const per=Number(data.transfersPerItem);if(!Number.isInteger(per)||per<0||per>100)throw Error('Transfers je Textil prüfen.');const l={...line(),transfersPerItem:per,description:r.name,vk:data.vk.trim()?Core.cents(data.vk):null,manualVk:manual&&!!data.vk.trim(),tax,ek:missingEk?Core.cents(data.ek):0,prices:structuredClone(r.prices||{}),manualEk:missingEk,source:r.source,sourceRow:r.row,vkSource:r.source,vkSourceRow:r.row};if(order().applicationMode===undefined&&!order().lines.some(x=>x.kind==='application'))order().applicationMode='auto';order().lines.push(l);copyDesign(order(),data.designSource,l.id);Core.reprice(order().lines);await save();$('#modal').close();view='orders';render();toast((l.vk==null?'Artikel mit offenem VK übernommen. Vor einem Angebot Preis festlegen. ':'Artikel übernommen: ')+r.model+' · '+l.color+' · '+l.size+' · '+l.qty+' Stück');});update();});}
